version: '3.8'

services:
  extracter:
    build:
      context: .
      dockerfile: Dockerfile_extract
    volumes:
      - ./data:/data

  transform_and_load:
    build:
      context: .
      dockerfile: Dockerfile.transform_load
    volumes:
      - ./data:/data
      - ./output:/clean_data
    depends_on:
      - extracter

volumes:
  data-volume:
  output-volume:

