name: Run Airflow DAG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push extracter image
        run: |
          docker build -t afrady/extracter_image -f Dockerfile_extract .
          docker push afrady/extracter_image

      - name: Build and push transform_and_load image
        run: |
          docker build -t afrady/transform_load_image -f Dockerfile.transform_load .
          docker push afrady/transform_load_image

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

      - name: Start Airflow
        run: |
          docker-compose up -d

      - name: Wait for Airflow to start
        run: sleep 60

      - name: Trigger Airflow DAG
        run: |
          curl -X POST "http://localhost:8080/api/v1/dags/docker_compose_dag/dagRuns" \
          -H "Content-Type: application/json" \
          -d '{"conf":{}}'
